CREATE TABLE BUS (
	BUSID INT PRIMARY KEY,
	DESTINATION VARCHAR(255) NOT NULL,
	SEATCOUNT INT NOT NULL
);

CREATE TABLE USERS (
	USERID INT PRIMARY KEY,
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	ROLEKEY VARCHAR(255)
);

CREATE TABLE SEAT (
	SEATID INT PRIMARY KEY,
	WIDTH INT NOT NULL,
	HEIGHT INT NOT NULL,
	RESERVED BOOL NOT NULL,
	BUSID INT NOT NULL,
	RESERVEDBYUSER INT,
	CONSTRAINT FK_BUS FOREIGN KEY (BUSID) REFERENCES BUS (BUSID),
	CONSTRAINT FK_RESERVEDBYUSER FOREIGN KEY (RESERVEDBYUSER) REFERENCES USERS (USERID)
);